

CREATE TABLE APPS.XX_LT_LOAN_DATA1
(
  SL                     NUMBER,
  ORG_ID                 NUMBER(15),
  BAL_SEG                VARCHAR2(10 BYTE),
  LOAN_ID                INTEGER,
  LOAN_NUMBER            VARCHAR2(50 BYTE),
  BANK_ID                NUMBER(15),
  BANK_BRANCH_ID         NUMBER(15),
  LOAN_TYPE_CODE         VARCHAR2(50 BYTE),
  LOAN_TYPE              VARCHAR2(50 BYTE),
  OPENING_DATE           DATE,
  MATURITY_DATE          DATE,
  INTEREST_RATE          NUMBER,
  ACCOUNTING_DATE        DATE,
  VOUCHER                NUMBER,
  CHARGE_TYPE            VARCHAR2(21 BYTE),
  DESCRIPTION            VARCHAR2(240 BYTE),
  LC_NUMBER              VARCHAR2(50 BYTE),
  DR_AMOUNT              NUMBER,
  CR_AMOUNT              NUMBER,
  FUNC_DR_AMOUNT         NUMBER,
  FUNC_CR_AMOUNT         NUMBER,
  MAJOR_LOAN_TYPE        VARCHAR2(30 BYTE),
  CURRENCY_CODE          VARCHAR2(15 BYTE),
  FOREIGN_CURRENCY_RATE  NUMBER,
  BANK_NAME              VARCHAR2(240 BYTE),
  BANK_BRANCH_NAME       VARCHAR2(240 BYTE),
  BANK_ACCOUNT_NAME      VARCHAR2(100 BYTE),
  YTD_DAY                NUMBER,
  LC_ID                  NUMBER(15)
)
TABLESPACE APPS_TS_TX_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX APPS.IND_LT_LOAN_DATA_ACC_DATE1 ON APPS.XX_LT_LOAN_DATA1
(TRIM(TO_CHAR("ACCOUNTING_DATE",'DD-MON-RR')))
LOGGING
TABLESPACE APPS_TS_TX_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX APPS.XX_LT_LOAN_DATA_ACC_DATE_IDX11 ON APPS.XX_LT_LOAN_DATA1
(BANK_ID, ORG_ID, LOAN_ID)
LOGGING
TABLESPACE APPS_TS_TX_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;
